### ISSUE TITLE
Change the endpoints workflow to commit changes instead of verifying if changes were made

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/.github#26]
I noticed we have a CI workflow to detect changes to a JSON file https://github.com/cloudquery/.github/blob/171977710ab1e8d6db4aa0ccbdcb2372e4101e58/workflows/repo-specific/cq-provider-aws/endpoints.yml#L25

Instead of detecting changes and failing the CI, we could auto commit the changes when the PR that generated those was opened.

For example, instead of:

```yaml
on:
  push:
    branches:
      - main
      
.....

      - name: Fail if file is changed
              run: |
                test "$(git status -s ./client/data/partition_service_region.json | wc -l)" -eq 0
```

We could:

```yaml
on:
  pull_request:
    branches:
      - main
      
.....
      - uses: actions/checkout@v3
        with:
          # A personal access token is required so to re-run the CI. See here https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ secrets.GH_CQ_BOT }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: fix: Sync endpoints
```

Happy to make the change if this makes sense to everyone
